summary: Get by Id
get:
    tags:
        - artists
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        artists:
                            value: |-
                                let data = [
                                    {id:1, name:"Alkem", country:"Estonia"}, 
                                    {id:2, name:"Jadeci", country:"USA"},
                                    {id:3, name:"Kanye West", country:"USA"},
                                    {id:4, name:"Island Boys", country:"USA"},
                                ]
            description: Succesful
        '404':
            description: Artist not found.
    summary: Get by Id
    description: Return all details of artists by Id.
parameters:
    -
        name: id
        in: path
        required: true
